openapi: 3.1.0

info:
  title: Carts API
  version: 1.0.0
  description: API for managing shopping carts in the store.

tags:
  - name: carts
    description: Cart related endpoints

paths: {}

components:
  schemas:
    CartId:
      type: string
      description: The unique identifier for a cart.
      example: "ZFe4yhG5qNhmuNyrbLWa4"
