openapi: 3.1.0

info:
  title: Simple Grocery Store API
  version: 1.0.0
  description: API for managing a simple grocery store.

tags:
  - name: status
    description: Status related endpoints

paths:
  /:
    get:
      summary: Welcome message
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome to the Simple Grocery Store API!"
  /status:
    $ref: "./status-api.yaml#/paths/~1status"

components:
  schemas:
    StatusResponse:
      $ref: "./status-api.yaml#/components/schemas/StatusResponse"
