openapi: 3.1.0

info:
  title: Simple Grocery Store API
  version: 1.0.0
  description: API for managing a simple grocery store.

paths:
  /:
    get:
      summary: Welcome message
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome to the Simple Grocery Store API!"
  /status:
    $ref: "./status-api.yaml#/paths/~1status"
  /products:
    $ref: "./products-api.yaml#/paths/~1products"
  /products/{productId}:
    $ref: "./products-api.yaml#/paths/~1products~1{productId}"
